language: node_js

node_js:
  - '11'

os:
  - osx
  - linux
  - windows

env:
  - YARN_GPG=no

cache:
  yarn: true

branches:
  only:
    - master

script:
  - yarn
  - ./build_files/rebuild_ext
  - yarn dist
  - ./build_files/upload_package
